### ISSUE TITLE
Config for base font size?

### ISSUE THREAD

**Issue by kanitw** [uwdata/vega-parser#18]
In https://github.com/vega/vega-lite/issues/1714, a user requested a way to change font size for the axis, legend, and facet, labels and titles all in one place.  

I don't have strong opinion if we should support this.  However, if we do, it seems like we should do this in Vega config rather than only for Vega-Lite config, so I'm moving the issue here.

**Comment by jheer** [comment]
All else being equal, it make sense to minimize the number of moving, interconnected parts. So I think we'll leave the config as-is (with separate entries for each axis/legend text mark) for now.

**Comment by slowkow** [comment]
Could I please ask you for help on changing the font size? For me, it does not seem to work. All of the fonts remain at the default size of 10px.

I'd like to change all of the fonts to be 20px by default.

Here is my code:

https://beta.observablehq.com/@slowkow/vega-lite-line-chart

```javascript
vegalite({
  data: {values: aapl},
  mark: {type: "line", interpolate: "step"},
  width,
  height: 360,
  autosize: "fit",
  title: {
    text: "blah",
    color: "#ff0000",
    fontSize: "20px",
    anchor: "start"
  },
  encoding: {
    x: {
      field: "date",
      type: "temporal",
      axis: {tickCount: 5, title: "Year", format: "%Y", fontSize: 20}
    },
    y: {
      field: "close",
      type: "quantitative",
      axis: {format: "$f", title: "AAPL Close", fontSize: 20}
    }
  }
})
```

**Comment by domoritz** [comment]
You need to use a number like `20` instead of a string `"20px"`. Also, setting the title font size is only supported in Vega-Lite 3, which we will release soon. I noticed a bug in Observable and will try to make a new release candidate to resolve this. 

<img width="1245" alt="screen shot 2018-08-08 at 18 03 23" src="https://user-images.githubusercontent.com/589034/43872451-99e1b496-9b36-11e8-8e79-a454801eefed.png">

**Comment by domoritz** [comment]
Here we go: https://beta.observablehq.com/@domoritz/fixed-vega-lite-line-chart

**Comment by slowkow** [comment]
Thank you! I tried `20` and it didn't work, so then I tried `"20px"` just in case. Thanks a lot for sharing your working notebook.

Could I also ask how to change the font size of axis titles and axis ticks?

The documentation for vega would be more helpful for me if it included explicit examples for each option.

For example, I haven't been able to infer how to use the config for text elements described here: https://vega.github.io/vega-lite/docs/text.html

Both of these attempts failed:

```javascript
axis: {tickCount: 5, title: {text:"Year", fontSize: 20}, format: "%Y"}
```

```javascript
axis: {tickCount: 5, title: "Year", fontSize: 20, format: "%Y"}
```

**Comment by domoritz** [comment]
The property is called `titleFontSize`. See https://vega.github.io/vega-lite/docs/axis.html#title. I recommend that you use https://vega.github.io/editor/, which has autocomplete and validates specs. I wonder whether we can somehow support autocomplete for Vega/Vega-Lite in Observable (cc @tmcw might have ideas). 

Regarding more example in the docs, please send us pull requests! We are always working on improving the docs but it's sometimes hard for us because we don't have the outside view.

**Comment by slowkow** [comment]
Thanks for pointing out the autocomplete and the editor.

I got the axis ticks to be larger with `labelFontSize` and axis titles to be larger with `titleFontSize`.

```javascript
vegalite({
  data: {values: aapl},
  mark: {type: "line", interpolate: "step"},
  width: width,
  height: 360,
  autosize: "fit",
  title: {
    text: "The Price of Apple",
    fontSize: 24,
    fontWeight: "normal",
    anchor: "start"
  },
  encoding: {
    x: {
      field: "date",
      type: "temporal",
      axis: {tickCount: 5, title: "Year", format: "%Y", titleFontSize: 20, labelFontSize: 20}
    },
    y: {
      field: "close",
      type: "quantitative",
      axis: {format: "$f", title: "AAPL Close", titleFontSize: 20, labelFontSize: 20}
    }
  }
})
```

**Comment by tmcw** [comment]
@domoritz It'd certainly be cool! I see that vega-editor's autocomplete is based on Monaco's LanguageServer implementation, whereas our editor is CodeMirror, mostly because CM has first-class support for mobile/touch interfaces. So unfortunately it's not a drop-in fix, or even a near-port. But certainly something I'll keep in mind.

**Comment by domoritz** [comment]
Yes, we use Monaco's built-in support for JSON schema. The schemas for Vega and Vega-Lite are at https://github.com/vega/schema. Vega-Lite is also written in Typescript (and we have typings for Vega) so that would be another option if it was supported.
