### ISSUE TITLE
modify expr function does not always update dataset

### ISSUE THREAD

**Issue by arvind** [uwdata/vega-parser#5]
With [this example](https://gist.github.com/arvind/0cb8a8e800b49489a0ec6cbe332efa99), and _again_ apologies I was not able to reproduce the issue with a more minimal one, the following behaviour is expected:

1. Brush within a cell of the SPLOM. 
2. Observe a grey rect corresponding to the brushed extents stored in the signal. 
3. Observe a red rect corresponding to the same extents stored in a backing dataset. 
4. Click anywhere within the same cell to "clear" the brush. 
5. Grey and red rects are no longer visible.

Note: due to vega/vega-scenegraph#33, the Canvas renderer must be used to observe the red rect.

While 1-5 typically executes correctly, I occasionally observe that on step 5, the grey rect disappears but the red rect remains.

**Comment by jheer** [comment]
Again: `"update": "modify('brush_selection', brush_tuple, brush_tuple)"`

**Comment by arvind** [comment]
So, this error seems to persist even after the changes made to `modify` in beta-7. I've updated the above example with new definitions for `brush_tuple` and the `modify` call as follows:

```json
        {
          "name": "brush_tuple",
          "on": [{
            "events": {"signal": "brush"},
            "update": "{$key: brush_id, brush: brush}"
          }]
        },
        {
          "name": "brush_trigger",
          "on": [{
            "events": {"signal": "brush"},
            "update": "modify('brush_selection', brush_tuple, {$key: brush_id})"
          }]
        }
```
Every so often, the grey rect will disappear but the red rect will persist.

**Comment by jheer** [comment]
Tracing through the dataflow, I eventually found that the error arises due to "faulty" signal propagation. The signal targeted by the modify update is sometimes not being evaluated. It is set to "skip" by the modify update, which is appropriate, but is then not being evaluated, which in this case should simply reset the skip condition. As a result, on the _next_ cycle, the modify expression is not evaluated due to the skip check in [on.js#L71](https://github.com/vega/vega-dataflow/blob/master/src/dataflow/on.js#L71). Hence the faulty update.

The problem goes away if I make the trigger update verbose (or, in Vega 3 parlance, `"force": true`):
```
{
  "name": "brush_trigger",
    "on": [{
      "events": {"signal": "brush"},
      "update": "modify('brush_selection', brush_tuple, {$key: brush_id})",
      "force": true
    }]
}
```

The "faulty" propagation is actually the correct behavior. What made this so tricky was that the issue only occurred sporadically; this is due to some questionable signal update return logic, which I will address in vega-dataflow (but you don't need to wait for that to employ the fix above).

Moral: signals with side-effects (as opposed to direct value propagation) can be tricky. Also, this was a case where using the new `warn` expression function was invaluable for getting the debug session moving forward productively!

**Comment by arvind** [comment]
Aha! I wonder how our debugging tools can better scaffold tracing this valid but unexpected/unintuitive behaviour. /cc @jhoffswell.
